# -*- coding: utf-8 -*-
"""ev_market_engineering_study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctb_EA3gtDbg7oMGqaPkPLCVDW-_DA2M

## Phase 1:

# Import Libraries
"""

# Import required libraries
import pandas as pd
import numpy as np

"""# Upload File in Google Colab"""

from google.colab import files
uploaded = files.upload()

"""# Read the Dataset"""

# Replace 'your_file_name.csv' with actual file name
df = pd.read_csv('electric_vehicles_spec_2025.csv.csv')

"""# Basic Data Understanding"""

# Shape of dataset
df.shape

# Column names
df.columns

# Data types
df.dtypes

# Info summary
df.info()

# Statistical summary
df.describe()

"""# Data Cleaning"""

# Check missing values
df.isnull().sum()

# Drop missing values (optional)
df = df.dropna()

# OR fill missing values
# df = df.fillna(0)

"""# Import Libraries & Load Data"""

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv('electric_vehicles_spec_2025.csv.csv')

"""# Convert Required Columns to NumPy Arrays"""

# Convert columns to numpy arrays
range_km = df['range_km'].to_numpy()
battery = df['battery_capacity_kWh'].to_numpy()
ev_names = df['model'].to_numpy()

avg_range = np.mean(range_km)
print("Average Range:", avg_range)

max_range = np.max(range_km)
print("Maximum Range:", max_range)

min_range = np.min(range_km)
print("Minimum Range:", min_range)

above_avg = np.sum(range_km > avg_range)
print("EVs above average range:", above_avg)

low_range = np.sum(range_km < 200)
print("EVs with range < 200 km:", low_range)

avg_battery = np.mean(battery)
print("Average Battery Capacity:", avg_battery)

best_index = np.argmax(range_km)
print("Best EV (Max Range):", ev_names[best_index], "-", range_km[best_index])

worst_index = np.argmin(range_km)
print("Lowest Range EV:", ev_names[worst_index], "-", range_km[worst_index])

filtered_range = range_km[battery > 70]
avg_filtered = np.mean(filtered_range)

print("Average Range (Battery > 70 kWh):", avg_filtered)

condition = (range_km > 400) & (battery > 70)
count_ev = np.sum(condition)

print("EVs with high range & battery:", count_ev)

# Convert efficiency column to numpy
efficiency = df['efficiency_wh_per_km'].to_numpy()

# Find index of minimum efficiency
min_eff_index = np.argmin(efficiency)

# Get EV name and value
print("Most Efficient EV (Lowest wh/km):")
print(ev_names[min_eff_index], "-", efficiency[min_eff_index])

# Filter condition
high_range_eff = efficiency[range_km > 400]

# Calculate average
avg_eff = np.mean(high_range_eff)

print("Average Efficiency (Range > 400 km):", avg_eff)

print("\nNumber of EVs with range > 400 km:", len(high_range_eff))

print("\n--- Project Summary ---")
print("Average Range:", avg_range)
print("Best EV:", ev_names[best_index])
print("Total High Performance EVs:", count_ev)

"""# Phase 2:

# import library and read the file
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

"""# Read the dataset"""

# Replace 'your_file_name.csv' with actual file name
df = pd.read_csv('electric_vehicles_spec_2025.csv')

"""1. Create efficiency_score & find highest"""

df["efficiency_score"] = df["range_km"] / df["battery_capacity_kWh"]

# EV with highest efficiency
highest_eff_ev = df.loc[df["efficiency_score"].idxmax()]

print(highest_eff_ev[["model", "efficiency_score"]])

"""2. Count EVs with efficiency_score > 6"""

count_eff = df[df["efficiency_score"] > 6].shape[0]
print("EVs with efficiency_score > 6:", count_eff)

"""3. Create performance_score & find highest"""

df["performance_score"] = (
    0.5 * df["range_km"] +
    0.3 * df["torque_nm"] -
    0.2 * df["acceleration_0_100_s"]
)

# Highest performance EV
top_perf_ev = df.loc[df["performance_score"].idxmax()]

print(top_perf_ev[["model", "performance_score"]])

"""4. Average performance_score (range > 400)"""

avg_perf = df[df["range_km"] > 400]["performance_score"].mean()

print("Average performance_score (range > 400):", avg_perf)

"""5. Top 3 EVs (performance_score)"""

top3_perf = df.sort_values(by="performance_score", ascending=False).head(3)

print(top3_perf[["model", "performance_score"]])

"""6. Bottom 3 EVs (performance_score)"""

bottom3_perf = df.sort_values(by="performance_score").head(3)

print(bottom3_perf[["model", "performance_score"]])

"""7. Top 5 EVs (range_km)"""

top5_range = df.sort_values(by="range_km", ascending=False).head(5)

print(top5_range[["model", "range_km"]])

"""8. 10th best EV (performance_score)"""

rank10_ev = df.sort_values(by="performance_score", ascending=False).iloc[9]

print(rank10_ev[["model", "performance_score"]])

"""9. 2nd highest efficiency_score"""

second_eff = df.sort_values(by="efficiency_score", ascending=False).iloc[1]

print(second_eff[["model", "efficiency_score"]])

"""10. New dataset (range + battery)"""

new_dataset = df[["range_km", "battery_capacity_kWh"]]

print(new_dataset.head())

"""# Phase 3:

# Random Sampling & Simulation

1. Random Sample of 5 EVs & Compare Averages
"""

import numpy as np

# Set seed for reproducibility (optional but professional)
np.random.seed(42)

# Generate 5 random indices
random_indices = np.random.choice(df.index, size=5, replace=False)

# Get sampled EVs
sample_evs = df.loc[random_indices]

print("Sampled EVs:\n")
print(sample_evs[["model", "range_km"]])

# Sample average range
sample_avg_range = sample_evs["range_km"].mean()

# Full dataset average range
full_avg_range = df["range_km"].mean()

print("\nSample Average Range:", sample_avg_range)
print("Full Dataset Average Range:", full_avg_range)

"""2. Battery Degradation Simulation & Analysis"""

# Generate random degradation values (0% to 20%)
df["battery_degradation_%"] = np.random.uniform(0, 20, size=len(df))

print("\nBattery Degradation Sample:\n")
print(df[["model", "battery_degradation_%"]].head())

# Filter EVs with degradation > 10%
high_deg_evs = df[df["battery_degradation_%"] > 10]

# Average range for those EVs
avg_range_high_deg = high_deg_evs["range_km"].mean()

print("\nAverage Range (Degradation > 10%):", avg_range_high_deg)